"""Derive every control arm from its parent, and write them to a separate file.

Two failures on 2026-08-23 motivate this. The evaluation block for the Vanilla
arm turned out to be a stale pre-v5 copy differing in twelve keys, eight of them
objective-level. And all six comparator arms carried
`per_action_carbon_weight = 0.5` against the main arms' 0.25, so each of them
optimised a different objective from the pair it was being compared with. Both
came from copying a config by hand. Nothing here is copied by hand.

Output goes to config_controls.yml rather than into config_C.yml: the G1 chain
re-reads the live config on every training, and the freeze manifest pins the
whole file's hash, so even appending an unrelated block would break the freeze
in form. Merge after G1, if at all.

Parents:
  risk arms and No-Forecast  <- matched Vanilla
  ablG and ablW              <- EU-CRD

ablG/ablW must come from EU-CRD. They ablate a component of EU-CRD, so a
matched-Vanilla parent would not have the component to remove.
"""
import argparse
import copy
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent
CONFIG = ROOT.parent / "config_C.yml"
OUT = ROOT.parent / "config_controls.yml"

VAN = "experiment_multi_5dc_carbon_v2_deferrable_gdpd_timecap_matchedvan"
EU = "experiment_multi_5dc_carbon_v2_deferrable_gdpd_timecap_eucrd_knSV3b"

# arm -> (parent, description, mutation). A mutation touches one leaf.
ARMS = {
    "experiment_ctrl_risk_cvar":  (VAN, "CVaR", ("crd", "risk", {"kind": "cvar", "alpha": 0.2, "lam": 0.5})),
    "experiment_ctrl_risk_mv":    (VAN, "mean-variance", ("crd", "risk", {"kind": "mean_variance", "lam": 1.0})),
    "experiment_ctrl_risk_rs":    (VAN, "risk-sensitive utility", ("crd", "risk", {"kind": "risk_sensitive", "beta": 1.0, "wmax": 5.0})),
    "experiment_ctrl_risk_dcvar": (VAN, "distributional CVaR", ("crd", "risk", {"kind": "dist_cvar", "alpha": 0.1, "lam": 0.7})),
    "experiment_ctrl_noforecast": (VAN, "No-Forecast", ("forecast_mode", None, "none")),
    "experiment_ctrl_ablG":       (EU,  "gate held open", ("crd", "blender", {"fixed_c": 1.0})),
    "experiment_ctrl_ablW":       (EU,  "no advantage reweighting", ("crd", "responsibility", {"reweight_advantages": False})),
}


def derive(cfg, name, parent, desc, mutation):
    block = copy.deepcopy(cfg[parent])
    top, sub, value = mutation
    if sub is None:
        block[top] = value
    else:
        block[top] = copy.deepcopy(block.get(top, {}))
        block[top][sub] = {**copy.deepcopy(block[top].get(sub, {})), **value}
    tag = name.replace("experiment_ctrl_", "")
    block["experiment_name"] = f"g1_control_{tag}"
    block["simulation_name"] = f"G1_control_{tag}"
    if isinstance(block.get("wandb"), dict):
        block["wandb"] = copy.deepcopy(block["wandb"])
        block["wandb"]["tags"] = sorted(set(block["wandb"].get("tags", [])) | {"g1_control", tag})
    return block


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--merge", metavar="PATH",
                    help="also write config_C.yml + the control blocks to PATH, "
                         "for running a control arm without touching the frozen file")
    args = ap.parse_args()

    cfg = yaml.safe_load(CONFIG.read_text())
    for parent in (VAN, EU):
        if parent not in cfg:
            sys.exit(f"parent missing from config_C.yml: {parent}")

    chunks = ["# GENERATED by drl-manager/make_control_arms.py. Do not hand-edit.\n"
              "# Every arm is derived from its parent block in config_C.yml by one leaf\n"
              "# mutation plus identity fields. Regenerate instead of editing, and let\n"
              "# tests/test_control_arms.py assert the difference sets.\n"]
    for name, (parent, desc, mutation) in ARMS.items():
        block = derive(cfg, name, parent, desc, mutation)
        short = "matched Vanilla" if parent == VAN else "EU-CRD"
        chunks.append(f"\n# {desc}. Derived from {short}.\n"
                      + yaml.safe_dump({name: block}, sort_keys=True, allow_unicode=True,
                                       default_flow_style=False))
    OUT.write_text("".join(chunks))
    print(f"wrote {OUT} with {len(ARMS)} arms")

    if args.merge:
        pathlib.Path(args.merge).write_text(CONFIG.read_text() + "\n" + OUT.read_text())
        print(f"merged runtime config -> {args.merge}")


if __name__ == "__main__":
    main()
