#!/usr/bin/env python3
"""Two Vanilla arms for the step-2 pilot: a clean forecast and a shrunk one.

DESIGN_PILOT. The numbers this produces are for designing Stage D and are not results.

The question is narrow and it is not "does the forecast help". It is: when the observation
channel carries a forecast that the shrink pilot already showed is actively harmful to a
planner, does a LEARNED policy get fooled by it, or does it learn to stop reading it and
recover by spreading work? The two answers point at different Stage D designs, so the pilot
is worth its wall clock either way.

Both arms are deep copies of one frozen DISCOVERY cell and differ from it only in the
whitelist below; between themselves they differ only in the tier and the two names. crd is
already disabled in the base, so "Vanilla" needs no edit -- it is asserted, not set.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
BASE_CONFIG = os.path.join(HERE, "config_s2e_discovery.yml")
BASE_CELL = "s2_r48_w72_c3_n35"
OUT = os.path.join(HERE, "config_rl_step2_pilot.yml")

ARMS = {"godeye": "godeye", "shrink50": "shrink50"}

# Everything the derivation may touch, relative to the frozen cell.
WHITELIST = {"experiment_name", "simulation_name", "green_oracle_mode", "perturb_tier",
             "wandb", "training"}
# Between the two arms, only these may differ.
ARM_WHITELIST = {"experiment_name", "simulation_name", "perturb_tier"}

# Confirmation-set turbines. The pilot must not touch them, and the check is mechanical
# rather than a promise.
CONFIRMATION_TURBINES = {52, 71, 47, 54, 3}


def base_block(path=BASE_CONFIG):
    cfg = yaml.safe_load(open(path))
    if BASE_CELL not in cfg:
        raise KeyError(f"{BASE_CELL} missing from {path}")
    return cfg[BASE_CELL]


def derive(base, arm, total_timesteps):
    b = copy.deepcopy(base)
    name = f"rlp2_{BASE_CELL}_{arm}"
    b["experiment_name"] = name
    b["simulation_name"] = f"RLP2_{name}"
    # The observation forecast now comes from the truth pushed through the ladder.
    b["green_oracle_mode"] = "perturbed_godeye"
    b["perturb_tier"] = ARMS[arm]
    b["training"] = dict(b["training"], total_timesteps=int(total_timesteps))
    # A pilot does not publish. The base block is wandb online, and two throwaway runs in
    # a shared project would look like results to anyone browsing it later.
    b["wandb"] = dict(b.get("wandb") or {}, enabled=False, mode="disabled")
    return b


def build(total_timesteps, path=BASE_CONFIG):
    base = base_block(path)
    if (base.get("crd") or {}).get("enabled", False):
        raise AssertionError("the frozen cell has crd enabled; this pilot is Vanilla only")
    turbines = {int(t) for dc in base["datacenters"] for t in (dc.get("turbine_ids") or [])}
    bad = turbines & CONFIRMATION_TURBINES
    if bad:
        raise AssertionError(f"confirmation turbines reached by the pilot cell: {sorted(bad)}")
    return {f"rlp2_{BASE_CELL}_{a}": derive(base, a, total_timesteps) for a in ARMS}


def diff_keys(a, b):
    return {k for k in set(a) | set(b) if a.get(k) != b.get(k)}


HEADER = ("# " + "-" * 76 + "\n"
          "# DESIGN_PILOT: step-2 pilot, Vanilla under a clean vs a shrunk forecast.\n"
          "# Generated by g1/compressed_timecap_s2/gen_rl_step2_pilot.py from the frozen\n"
          "# DISCOVERY cell s2_r48_w72_c3_n35. Do not hand edit.\n"
          "# Numbers from these arms are design input, not results, and are not citable.\n"
          "# " + "-" * 76 + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--total-timesteps", type=int, default=100_000)
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    blocks = build(a.total_timesteps)
    base = base_block()
    for n, b in blocks.items():
        print(f"{n}: tier={b['perturb_tier']} steps={b['training']['total_timesteps']} "
              f"diff={sorted(diff_keys(base, b))}")
    if not a.write:
        print("dry run; pass --write")
        return
    with open(OUT, "w") as f:
        f.write(HEADER)
        yaml.safe_dump(blocks, f, default_flow_style=False, sort_keys=True,
                       allow_unicode=True, width=4096)
    print(f"wrote {OUT}  sha256="
          f"{hashlib.sha256(open(OUT,'rb').read()).hexdigest()[:16]}")


if __name__ == "__main__":
    main()
