_wandb:
    value:
        cli_version: 0.23.0
        e:
            qswtnawy75tup14ecsr0jtmzktf21ria:
                args:
                    - --config
                    - /tmp/config_crd_smoke.yml
                    - --experiment
                    - experiment_multi_5dc_carbon_v2
                    - --total-timesteps
                    - "8000"
                    - --num-gpus
                    - "0"
                    - --output-dir
                    - /tmp/crd_smoke_output
                codePath: drl-manager/entrypoint_rlmodule_gtrxl.py
                codePathLocal: entrypoint_rlmodule_gtrxl.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "97829425152"
                        used: "39576256512"
                email: qwe292387082@gmail.com
                executable: /home/joshua/rl-cloudsimplus-greenscheduling/drl-manager/.venv/bin/python
                git:
                    commit: 623a1cbd6c6e1b38acc61ed6dcd083dfc4493aae
                    remote: git@github.com:FCBayern1/rl-cloudsimplus-greenscheduling.git
                gpu: NVIDIA GeForce RTX 5080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 10752
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5080
                      uuid: GPU-e7559356-56be-3ebb-e280-677e90c8ed56
                host: joshua-B850M-AORUS-ELITE
                memory:
                    total: "64900100096"
                os: Linux-6.17.0-29-generic-x86_64-with-glibc2.39
                program: /home/joshua/rl-cloudsimplus-greenscheduling/drl-manager/entrypoint_rlmodule_gtrxl.py
                python: CPython 3.12.3
                root: /home/joshua/rl-cloudsimplus-greenscheduling/drl-manager
                startedAt: "2026-05-25T10:21:00.510058Z"
                writerId: qswtnawy75tup14ecsr0jtmzktf21ria
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 30
                - 105
            "2":
                - 1
                - 30
                - 105
            "3":
                - 2
                - 5
                - 13
                - 14
                - 15
                - 62
            "4": 3.12.3
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
